version: "3.9"

services:
  backend:
    build: ./backend
    container_name: aqi_backend
    env_file:
      - .env
    environment:
      # Spring Boot reads this env var
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      # optional: SERVER_PORT=8080
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: aqi_frontend
    working_dir: /app
    env_file:
      - .env
    environment:
      # INSIDE docker, talk to backend via service DNS, not localhost
      VITE_API_BASE: http://backend:8080
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    restart: unless-stopped
