server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aqidb}
    username: ${SPRING_DATASOURCE_USERNAME:aqi_user}
    password: ${SPRING_DATASOURCE_PASSWORD:aqi_pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

app:
  cacheTtlMinutes: 60
